### ISSUE TITLE
🗺 Geo-location picker

### ISSUE THREAD

**Issue by ChristopherJennings** [Kentico/custom-element-samples#14]
### Motivation

Make it easy for content editors to enter a precise location (latitude and longitude) without needing to know what latitude and longitude is. 

### Proposed solution

Present a **Google maps** address search box and map to allow an editor to search for and refine the selected location. The value of the entered address and lat/long are stored. 

### Resources
* https://developers.google.com/maps/documentation/javascript/examples/places-searchbox

**Comment by ChristopherJennings** [comment]
I'm interested in building this.

**Comment by maartenvdh** [comment]
Why does this have the tag "up-for-grabs" and it is assigned to Christopher? If nobody is doing this I like to build this one.

**Comment by Simply007** [comment]
Hello @maartenvdh,

thank you for notifying us, I have removed the label from the issues taken.

I am assuming @ChristopherJennings is about to do this custom element - right @ChristopherJennings?

Feel free to take another issue, or create an element you think could be useful and submit a pull request, just mind already implemented elements or in the ones pull request state.

**Comment by maartenvdh** [comment]
Thanks @Simply007 for the quick response, I am now busy with a Flickr image selector element. When I am ready I will submit a pull request.

**Comment by ChristopherJennings** [comment]
@Simply007 I am working on this. Probably 70-80% complete.

**Comment by Simply007** [comment]
@maartenvdh - adding the link to the appropriate issue: #37

**Comment by maartenvdh** [comment]
> @Simply007 I am working on this. Probably 70-80% complete.

@ChristopherJennings still busy with this one? do you like me to help you with this?

**Comment by ChristopherJennings** [comment]
It's on my list for today actually. If for whatever reason I don't end up making a PR for this by the eod of this week, feel free to take it up.

**Comment by ChristopherJennings** [comment]
Merged.
