### ISSUE TITLE
📜 JS Fiddle selector

### ISSUE THREAD

**Issue by petrsvihlik** [Kentico/custom-element-samples#15]
### Motivation

A technical author (developer evangelist) wants to showcase a piece of JavaScript code in their article. They want to use the best tools available so they choose to use [JS Fiddle](https://jsfiddle.net/). They want to include the fiddle in their article without losing their focus and the context of the Kentico Cloud UI.

### Proposed solution

- Get a username of a currently logged-in user https://docs.jsfiddle.net/api/get-username
- Use https://docs.jsfiddle.net/api/displaying-user-fiddles to retrieve user's fiddles
- Let the user choose one from the list of fiddles

### Alternatives
- You can choose whatever fiddle you like: https://fiddles.io/

**Comment by MilanLund** [comment]
Wanted to take that one. Regrettably, the JSFiddle API seems to be a bit crappy. Requests get blocked by CORS policy. 
For the https://jsfiddle.net/user/get_username/ endpoint, I get the correct result only when requested from the browser address bar. When requesting from code, I get an empty string.
For the https://jsfiddle.net/api/user/milanlund/demo/list.json endpoint, I get empty array even if there are saved fiddles in my account.
Could anyone prove or disprove my findings? And possibly find a workaround?

**Comment by petrsvihlik** [comment]
@makma could you please take a look?

**Comment by makma** [comment]
I'm afraid @MilanLund is right, the JSFiddle's API does not set `Access-Control-Allow-Origin` response header so it's not possible to get and access response from JSFiddle's API (via `XMLHttpRequest` or `fetch` API) from Kentico's or localhost's origin.

**Comment by petrsvihlik** [comment]
closing as blocked
