### ISSUE TITLE
👨‍👩‍👦 Optimizely audience picker

### ISSUE THREAD

**Issue by petrvozak** [Kentico/custom-element-samples#3]
Content editor can assign audiences from Optimizely to the content entry to define what content entry is relevant for what audience. Developer can then use this information and information about the visitor from Optimizely to deliver the right content to the right audience (content personalization).

### Accept criteria
Multiple audiences can be assigned to a content entry

### Proposed solution
A custom element allowing to select audiances from Optimizely

### Useful resources
About Optimizely: https://www.optimizely.com/
About audiences in Optimizely: https://help.optimizely.com/Target_Your_Visitors/Audiences%3A_Choose_which_visitors_to_include
Dev docs: https://developers.optimizely.com/overview/

**Comment by kenticomartinh** [comment]
Being handled with internal integrations how to

PR with the implementation: https://github.com/Kentico/custom-element-samples/pull/20

**Comment by ChristopherJennings** [comment]
This has been merged. The issue should be closed.

**Comment by Simply007** [comment]
Fixed by #20
