### ISSUE TITLE
🖼️ Flicker image picker

### ISSUE THREAD

**Issue by petrsvihlik** [Kentico/custom-element-samples#37]
The content editor can search and fetch file(s) from external image hosting service and video hosting service without leaving Kentico admin UI. Developer can then use API to make the files part of the content item output presentation to provide complete information to the content consumer.

### Proposed solution
A custom element allowing to search and fetch file(s) from **Flickr** digital asset management system

### Useful resources
About listing: https://www.flickr.com/
Service liflistingtin: https://www.flickr.com/services/ 
API Documentation: https://www.flickr.com/services/api/
Developer guide: https://www.flickr.com/services/developer

**Comment by maartenvdh** [comment]
I like to pick this up :-)
