### ISSUE TITLE
🛒 Shopify product picker

### ISSUE THREAD

**Issue by petrvozak** [Kentico/custom-element-samples#4]
When I'm managing product raw data (SKU, price, etc. ) in Shopify and product rich multichannel content (descriptions, multimedia, etc.) in Kentico Cloud and when I'm creating a new rich content in Kentico Cloud related to specific product managed in Shopify I want to reference that product in the content item created, so that I can tell the system what rich content belongs to what product. Developer can then use this information to deliver the complete product information to the output channel(s).

### Proposed solution
A custom element allowing to search and pick a product from Shopify

### Accept criteria
A product name and image of the selected product is displayed

### Useful resources
About Shopify: https://www.shopify.com/
Shopify dev resources: https://developers.shopify.com/

**Comment by kenticomartinh** [comment]
PR with simple Shopify product selector, being handled internally as a part of related integration article

https://github.com/Kentico/custom-element-samples/pull/19

**Comment by Simply007** [comment]
fixed by #19
