### ISSUE TITLE
📜 Code editor with syntax highlighting

### ISSUE THREAD

**Issue by petrvozak** [Kentico/custom-element-samples#8]
Developer can write code samples with syntax highlighting to avoid mistakes, e.g. while writing a block of sample code for an article.

### Proposed solution
A custom element allowing to write a code in Ace code editor

### Useful resources
About Ace code editor and its API: https://ace.c9.io/

**Comment by MilanLund** [comment]
I take this one.

**Comment by petrsvihlik** [comment]
it's yours @MilanLund ! ;)
